# fly.toml app configuration file generated for full-stack-open-pokedex-stylized-substance on 2024-05-29T11:15:29+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-stylized-substance'
primary_region = 'ams'

[build]

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 3000 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "10s"
  method = "GET"
  timeout = "5s"
  path = "/health"


[deploy]
  strategy = "canary"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
